### ISSUE TITLE
Insert data into database

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/database#3]
use existing data from https://github.com/hitontology/ontology

- [x] convert catalogues and standards from https://github.com/hitontology/csv2rdf in issue #5
- [x] load external data over SPARQL in issue #4
- [x] load software products over SPARQL in issue #8

**Comment by ThomasPause** [comment]
done.

**Comment by KonradHoeffner** [comment]
Citations fehlen noch.

**Comment by KonradHoeffner** [comment]
jetzt aber wirklich fertig
